include: package:flutter_lints/flutter.yaml

# https://dart-lang.github.io/linter/lints/index.html.
linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
    avoid_redundant_argument_values: true
    use_super_parameters: true
    directives_ordering: true
