name: e1547_clynamic
description: e1547 landing page

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  url_strategy: ^0.2.0
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.11
  expandable: ^5.0.1
  seo_renderer: ^0.6.0
  anchor_scroll_controller: ^0.4.3
  backdrop: ^0.9.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

  # flutter pub run flutter_native_splash:create
  flutter_native_splash: ^2.2.19

flutter:
  uses-material-design: true
  assets:
    - app-icon.png
    - app-banner.png
    - screenshots/
    - altstore.json

flutter_native_splash:
  color: "#FDB245"
  image: "app-icon.png"
