name: clynamic
description: clynamic website

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter_custom_clippers: ^2.0.0
  expandable: ^5.0.1
  seo_renderer: ^0.6.0
  font_awesome: ^5.10.1
  anchor_scroll_controller: ^0.3.2
  backdrop: ^0.7.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

  # flutter pub run flutter_native_splash:create
  flutter_native_splash: ^2.1.3+1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/screenshots/

flutter_native_splash:
  color: "#FDB245"
  image: "assets/app-icon.png"
