name: build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup actions
        uses: actions/checkout@v3

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: get dependencies
        run: flutter pub get

      - name: build release
        run: flutter build web
      
      - name: package release
        run: |
          cd build/web
          zip -9 -r release.zip build/web/*
          mv release.zip ../../

      - name: upload release to assets
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
