name: Build on Push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: setup actions
      uses: actions/checkout@v3

    - name: setup flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable' 

    - name: get dependencies
      run: flutter pub get

    - name: build release
      run: flutter build web
      
    - name: package release
      run: |
        zip -9 -r release.zip build/web

    - name: upload assets
      uses: actions/upload-artifact@v3
      with:
        name: release-zip
        path: release.zip
